### ISSUE TITLE
Perhaps using Gitter for discussion items

### ISSUE THREAD

**Issue by gostlund** [scytherswings/Network-Status-Page#17]
Hey, I'd love to help with some of the testing and implementation stuff, especially on your new project, though I think this is something closer to what I need than the PlexBoard, because I would like to use the pfSense integration features still...  If that's still something that's likely to be a component of the PlexBoard then I'm all for it... I'm sure it'd be quite handy to have a Gitter (https://gitter.im) room for discussions on the projects, and it would make it much easier to chat about them... Anyway, I'm going to have my hands full initially as I have to make a docker container for this (for using on my unRAID server) but then tying it into my Plex, Deluge, Couchpotato, SABnzbd, and Sonarr systems... Should be a good challenge...

**Comment by scytherswings** [comment]
Hey sorry it took so long for me to respond to your message, I've been pretty busy lately (especially since I'm trying to get Plex-Board ready for 0.1 release this weekend) on top of my day job. If you want to help, please, feel free! You can fork my project and then do a pull-request and we'll merge in the changes, or I can add you as a contributor if you'd like. Also, I just set up some Gitter chat rooms, I've never used it before so this is new to me.
